config/routes.rb
Rails.application.routes.draw do

 
 resources :welcome
 
 resources :rooms do
    resources :employees
  end
 
 resources :reservations
 
 resources :customers

 

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  belongs_to :reservation
  belongs_to :room
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :reservation
  belongs_to :room
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  
  belongs_to :room
  has_many :employees
  
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :reservations
	has_many :employees
	has_many :customers
end

app/controllers/agent_controller.rb
class AgentController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

	def new
		
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  def new
  		@employee = Employee.new
  end

  def show
      
  end	

  def create
    @room = Room.find(params[:room_id])
    @employee = @room.employees.create(employee_params)
    redirect_to room_path(@room)
  end
 
  private
    def employee_params
      params.require(:employee).permit(:nameEm)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def index
		@reservation = Reservation.all
		
	end

	def new
		@reservation = Reservation.new
	end

	def edit
  		@reservation = Reservation.find(params[:id])
	end

	def create
  		@reservation = Reservation.new(reservation_params)
 
  		@reservation.save
  		redirect_to @reservation
	end

	def show
		@reservation = Reservation.find(params[:id])
	end

	def update
		@reservation = Reservation.find(params[:id])
 
  		@reservation.update(reservation_params)
    	redirect_to @reservation
	end

	def destroy
    	@reservation = Reservation.find(params[:id])
    	@reservation.destroy
 
    	redirect_to reservations_path
  	end

	private
  		def reservation_params
    		params.require(:reservation).permit(:roomRes, :time)
  		end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

	def index
		@room = Room.all
		
	end

	def show
		@room = Room.find(params[:id])	
	end

	def new
		@room = Room.new		
	end

	def edit
  		@room = Room.find(params[:id])
	end

	def create
  		@room = Room.new(room_params)
 
  		@room.save
  		redirect_to @room
	end

	def update
		@room = Room.find(params[:id])
 
  		@room.update(room_params)
    	redirect_to @room
	end

	def destroy
    	@room = Room.find(params[:id])
    	@room.destroy
 
    	redirect_to rooms_path
  	end
 
	private
  		def room_params
    		params.require(:room).permit(:room)
  		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/agent_helper.rb
module AgentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/new.html.erb
<h1>Customers</h1>
<p>
	<%= link_to 'Rooms', new_room_path(@room) %> 
</p>

app/views/employees/_employee.html.erb
<p>
  <strong>NameEmployee:</strong>
  <%= employee.nameEm %>
</p>

app/views/employees/new.html.erb
<h1>Employee</h1>

<h2>Add Employee:</h2>

<% @room = Room.create %>
<% @employee = Employee.new %>
<%= form_for [@room, @employee] do |a| %>
  <p>
    <%= a.label :Name %><br>
    <%= a.text_field :nameEm %>
  </p>
 
  <p>
    <%= a.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/_form.html.erb
<%= form_for @reservation do |r| %>
  <p>
    <%= r.label :Room %><br>
    <%= r.text_field :roomRes %>
  </p>

  <p>
    <%= r.label :Date %><br>Exp.01/01/2016<br>
    <%= r.text_field :time %>
  </p>
 
  <p>
    <%= r.submit %>
  </p>
<% end %>

app/views/reservations/edit.html.erb
<h1>Edit Reservation Room</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', reservations_path %>
</p>

app/views/reservations/index.html.erb
<h2>List Reservation </h2>

<p>
  <%= link_to 'Add Reservation', new_reservation_path(@room) %> 
</p>

<table>
  <tr>
    <th>Room</th>
    <th>Date</th>
    <th colspan="2"></th>
  </tr>
 
  <% @reservation.each do |reservation| %>
    <tr>
      <td><%= reservation.roomRes %></td>
      <td><%= reservation.time %></td>
      <td><%= link_to 'Show', reservation_path(reservation) %></td>
      <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
      <td><%= link_to 'Delete', reservation_path(reservation),method: :delete %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Back Home', welcome_index_path(@welcome) %> 
</p>

app/views/reservations/new.html.erb
<h1>Reservation Room</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', rooms_path %>
</p>

app/views/reservations/show.html.erb
<h1>Reservation</h1>
<p>
  <strong>Room:</strong>
  <%= @reservation.roomRes %>
</p>
<p>
  <strong>Date:</strong>
  <%= @reservation.time %>
</p>

<%= link_to 'Back', reservations_path %>

app/views/rooms/_form.html.erb
<%= form_for @room do |f| %>
  <p>
    <%= f.label :Room %><br>
    <%= f.text_field :room %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>


<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Hotel</h1>

<p>
	<%= link_to 'Add Check In', new_room_path(@room) %> 
</p>



<table>
  <tr>
    <th>Rooms</th>
  </tr>
 
  <% @room.each do |room| %>
    <tr>
      <td><%= room.room %></td>
      <td><%= link_to 'Show', room_path(room) %></td>
      <td><%= link_to 'Edit', edit_room_path(room) %></td>
      <td><%= link_to 'Delete', room_path(room),method: :delete %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Back Home', welcome_index_path(@welcome) %> 
</p>

app/views/rooms/new.html.erb
<h1>Check In</h1>

<%= render 'form' %>

<p>
	<%= link_to 'Back', rooms_path %>
</p>
<p>
	<%= link_to 'Employees', new_employee_path(@employee) %> 
</p>

app/views/rooms/show.html.erb
<h1>Hotel</h1>
<p>
  <strong>Room:</strong>
  <%= @room.room %>
</p>
<h2>Employee</h2>

	
<%= link_to 'Add employee', new_room_employee_path(@room) %>
<%= link_to 'Back', rooms_path %>

app/views/welcome/index.html.erb
<h1>Hotel Welcome</h1>
<p>
	<%= link_to 'Check In', rooms_path(@room) %> 
</p>

<p>
	<%= link_to 'Add Reservation', reservations_path(@reservation) %> 
</p>